# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-08 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='deliver_address',
            new_name='delivery_address',
        ),
    ]
