# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-12 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200108_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', '正在租借'), ('1', '已归还')], default='0', max_length=2),
        ),
    ]
